#Truly Dark properties file
#Sun Oct 04 16:41:35 UTC 2026
dark_nether_fog=0.5
only_affect_block_light=false
dark_overworld=true
dark_default=true
biome_blacklist=alexscaves\:primordial_caves,alexscaves\:candy_cavity
moon_phase_4=0.0
moon_phase_5=0.0
dark_nether=true
starlight=0.0
moon_phase_2=0.0
moon_phase_3=0.0
moon_phase_6=0.0
moon_phase_7=0.0
setup_version=Manual
dark_end_fog=0.0
moon_phase_0=0.0
moon_phase_1=0.0
dark_end=true
dark_skyless=true
