name = "othersmaybehere"
author = "<o>"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27f406c2d801aeb757db79d9d7f243b0df2a51f8fbb823254b32cbfbcfaf9fb2"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
