name = "othersmaybehere"
author = "<o>"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79a520397bfc9bff1a03209826cd8fb2bd929b6b871b662c556a4d4287725ce7"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
