name = "othersmaybehere"
author = "<o>"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abfff157ff248844bed7b0ef0be4de50d1feab8fa3b74bf1531974ff2f57b3c7"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
