#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Oct 04 15:39:55 UTC 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
