name = "othersmaybehere"
author = "<o>"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c29ef97881fa9a1a48e015c9e109497559e637aafa3cbf6191a80e66d2addf3f"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
