name = "othersmaybehere"
author = "<o>"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a0442228f4667ca52889c2eec32b75a7bc7397509fcce2e3bf9dabcb6107e8e"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
