name = "othersmaybehere"
author = "<o>"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d229a29574dbb121eb14edbcbd2f037418d737e8eede35e8a4c1cfd2b51af39"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
